apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o7a8ssqgr-java-quarkus
  janus-idp.io/tekton: o7a8ssqgr-java-quarkus
  backstage.io/kubernetes-id: o7a8ssqgr-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o7a8ssqgr-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
